### ISSUE TITLE
Missing enclosure tag?

### ISSUE THREAD

**Issue by clemlatz** [csellis/gatsby-plugin-podcast-feed#3]
I'm trying to host a podcast using gatbsy and your plugin, following the README "How to use" instructions. RSS generating works great, but once subscribed on iTunes, my podcast does not show any available episode. I think an RSS entry must contain the mp3 url as [an `enclosure` tag](https://en.wikipedia.org/wiki/RSS_enclosure) to be recognized as a podcast episode.

I'm not sure if I'm doing something wrong or if this is a bug in the plugin.

Here's an example markdown entry in my feed:

```markdown
---
number: 1
title: "La Bibliothèque Orbitale - Episode 87 - Utopiales 2019"
slug: "La-Bibliotheque-Orbitale-Episode-87"
date: "2019-11-13"
url: https://blog.belial.fr/media/Podcast/BO_87.mp3
categories:
  - Podcast
---

Peut-être n'y avez-vous pas fait attention mais la Bibliothèque orbitale s'est posée à Nantes lors des Utopiales. Notre chroniqueur spatial, Philippe Boulier, en a profité pour attraper un rhume ainsi que l'anthologie annuelle du festival — choses dont il nous propose le compte-rendu détaillé…
```

Here's the generated XML for this particular entry:

```xml
<item>
<title>
La Bibliothèque Orbitale - Episode 87 - Utopiales 2019
</title>
<description>
Peut-être n'y avez-vous pas fait attention mais la Bibliothèque orbitale s'est posée à Nantes lors des Utopiales. Notre chroniqueur spatial…
</description>
<link>https://blog.belial.fr/media/Podcast/BO_87.mp3</link>
<guid isPermaLink="false">f8c57661-c2d2-5361-8130-ff6c57bb9ef9</guid>
<category>Podcast</category>
<dc:creator>Philippe Boulier</dc:creator>
<pubDate>Wed, 13 Nov 2019 00:00:00 GMT</pubDate>
<content:encoded>
<p>Peut-être n'y avez-vous pas fait attention mais la Bibliothèque orbitale s'est posée à Nantes lors des Utopiales. Notre chroniqueur spatial, Philippe Boulier, en a profité pour attraper un rhume ainsi que l'anthologie annuelle du festival — choses dont il nous propose le compte-rendu détaillé…</p>
</content:encoded>
<pubDate>2019-11-13</pubDate>
<itunes:explicit>no</itunes:explicit>
<itunes:episodeType>full</itunes:episodeType>
<itunes:title>
La Bibliothèque Orbitale - Episode 87 - Utopiales 2019
</itunes:title>
<itunes:episode>1</itunes:episode>
<itunes:summary>
Peut-être n'y avez-vous pas fait attention mais la Bibliothèque orbitale s'est posée à Nantes lors des Utopiales. Notre chroniqueur spatial…
</itunes:summary>
<itunes:author>Philippe Boulier</itunes:author>
<itunes:image href="http://www.belial.fr/belial/media/layout/bibliotheque-orbitale.jpg"/>
</item>
```

Just FYI, here's a working example of a RSS entry in another podcast feed, including the enclosure tag:

```xml
<item>
<title>
Séisme du Teil : quelle est son origine et son impact sur les centrales nucléaires ?
</title>
<link>
</link>
<description>
durée : 00:04:59 - La chronique "Detox" de Caroline Tourbe - par : Caroline TOURBE - Le 11 novembre dernier, un séisme d’une magnitude de 5 secoue le village du Teil, situé à quelques kilomètres de Montélimar. Un tremblement de terre qui va provoquer des blessés et des dégâts importants.
</description>
<author>podcast@radiofrance.com</author>
<category>Science Nature</category>
<enclosure url="http://rf.proxycast.org/1638439899138891776/10212-15.11.2019-ITEMA_22203892-1.mp3" length="4819271" type="audio/mpeg"/>
<guid>c12c2c8e-74c3-43e3-96ac-1b1352cb144f</guid>
<pubDate>Fri, 15 Nov 2019 14:12:00 +0100</pubDate>
<podcastRF:businessReference>36669</podcastRF:businessReference>
<podcastRF:magnetothequeID>2019F36669S0319</podcastRF:magnetothequeID>
<itunes:title>
Séisme du Teil : quelle est son origine et son impact sur les centrales nucléaires ?
</itunes:title>
<itunes:author>Caroline TOURBE</itunes:author>
<itunes:explicit>no</itunes:explicit>
<itunes:keywords>
Séisme,du,Teil,:,quelle,est,son,origine,et,son,impact,sur,les,centrales,nucléaires,?,
</itunes:keywords>
<itunes:subtitle>
Séisme du Teil : quelle est son origine et son impact sur les centrales nucléaires ?
</itunes:subtitle>
<itunes:summary>
durée : 00:04:59 - La chronique "Detox" de Caroline Tourbe - par : Caroline TOURBE - Le 11 novembre dernier, un séisme d’une magnitude de 5 secoue le village du Teil, situé à quelques kilomètres de Montélimar. Un tremblement de terre qui va provoquer des blessés et des dégâts importants.
</itunes:summary>
<itunes:duration>00:04:59</itunes:duration>
<googleplay:block>yes</googleplay:block>
</item>
```

**Comment by clemlatz** [comment]
Further investigating... I tried to follow the [rss](https://www.npmjs.com/package/rss) package convention as the README recommends and add an `enclosure` to my entry frontmatter header:

```yaml
---
number: 1
title: "La Bibliothèque Orbitale - Episode 87 - Utopiales 2019"
slug: "La-Bibliotheque-Orbitale-Episode-87"
date: "2019-11-13"
url: https://blog.belial.fr/media/Podcast/BO_87.mp3
categories:
  - Podcast
enclosure:
  url: https://blog.belial.fr/media/Podcast/BO_87.mp3
  size: 123456789
  type: audio/mpeg
---

Peut-être n'y avez-vous pas fait attention mais la Bibliothèque orbitale s'est posée à Nantes lors des Utopiales. Notre chroniqueur spatial, Philippe Boulier, en a profité pour attraper un rhume ainsi que l'anthologie annuelle du festival — choses dont il nous propose le compte-rendu détaillé…
```

But still no luck, as the `enclosure` field seems to be ignored.
